### ISSUE TITLE
Have experience with GitHub & Git

### ISSUE THREAD

**Issue by keshavseksaria** [keshavseksaria/GSoC-pgRouting#2]
- [x] Fork the [GSoC-pgRouting](https://github.com/pgRouting/GSoC-pgRouting) repository
- [x] activate issues in your fork
- [x] open an issue in your fork and put this content on the issue
- [x] Clone your fork repository in your computer
- [x] Create remote named `upstream` pointing to https://github.com/pgRouting/pgrouting
- [x] checkout to the master branch of `upstream`
- [x] create new branch with name `gsoc-test`
- [x] push the newly created branch
- [x] put link of branch on pgRouting gitter chat
- [x] put link of issue on pgRouting gitter chat

**Comment by keshavseksaria** [comment]
# Create remote named upstream

git remote add upstream https://github.com/pgRouting/pgrouting
git remote -v


![Screenshot from 2020-02-25 02-36-50](https://user-images.githubusercontent.com/33085252/75191406-45fb2380-5778-11ea-9a4b-676c54000a2c.png)

**Comment by keshavseksaria** [comment]
# Checkout to the master branch of `upstream`

git fetch --all
git checkout upstream/master
git branch

![Screenshot from 2020-02-25 11-54-51](https://user-images.githubusercontent.com/33085252/75221146-1c1d1d80-57c7-11ea-9659-976809ae507e.png)

**Comment by keshavseksaria** [comment]
# Create new branch with name gsoc-test
git checkout -b gsoc-test

![Screenshot from 2020-02-25 12-09-18](https://user-images.githubusercontent.com/33085252/75221559-268be700-57c8-11ea-9d70-ac6112e9cff1.png)

**Comment by keshavseksaria** [comment]
# Push the newly created branch

git push origin gsoc-test

![Screenshot from 2020-02-25 12-29-59](https://user-images.githubusercontent.com/33085252/75222666-bb8fdf80-57ca-11ea-801b-229667bb7499.png)

**Comment by cvvergara** [comment]
Please dont put images of text


this passed.

**Comment by keshavseksaria** [comment]
Sure, i will keep that in mind.
