### ISSUE TITLE
Build locally pgRouting

### ISSUE THREAD

**Issue by keshavseksaria** [keshavseksaria/GSoC-pgRouting#3]
- [x] Install requirements
- [x] create new branch with name `gsoc-test`
- [x] push the newly created branch
- [x] build locally pgRouting
- [x] put link of issue on pgRouting gitter chat

**Comment by keshavseksaria** [comment]
```
mkdir build
cd build
cmake ..
make
```

Screenshots of local build

![Screenshot from 2020-02-25 19-38-51](https://user-images.githubusercontent.com/33085252/75254804-ee57c900-5806-11ea-8353-f9260d2c109e.png)
![Screenshot from 2020-02-25 19-39-08](https://user-images.githubusercontent.com/33085252/75255061-5efee580-5807-11ea-83d0-70e8830b9256.png)
![Screenshot from 2020-02-25 19-39-16](https://user-images.githubusercontent.com/33085252/75255067-61613f80-5807-11ea-96c6-bff1735da290.png)
![Screenshot from 2020-02-25 19-39-23](https://user-images.githubusercontent.com/33085252/75255072-645c3000-5807-11ea-910b-a21f2d74ce96.png)
![Screenshot from 2020-02-25 19-39-32](https://user-images.githubusercontent.com/33085252/75255076-658d5d00-5807-11ea-9afd-aa1d93880d37.png)
![Screenshot from 2020-02-25 19-39-38](https://user-images.githubusercontent.com/33085252/75255081-66be8a00-5807-11ea-91cd-81882eb796b5.png)
![Screenshot from 2020-02-25 19-39-46](https://user-images.githubusercontent.com/33085252/75255088-67efb700-5807-11ea-8292-298a329af4c4.png)

**Comment by cvvergara** [comment]
This passed
